# Generated by Django 3.2.9 on 2022-01-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220118_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='question',
        ),
    ]
