# Generated by Django 3.2.9 on 2021-12-13 08:16

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_indexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=None, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='text',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default=None),
        ),
    ]
