# Generated by Django 3.2.9 on 2022-01-18 13:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220118_1042'),
        ('pages', '0002_alter_blogpage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='text',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('polls', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(required=True))]))], default=None),
        ),
    ]
