# Generated by Django 3.2.9 on 2021-12-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211220_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
