# Generated by Django 3.2.9 on 2021-12-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211213_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='number',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='body',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
