# Generated by Django 3.2.9 on 2021-12-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20211213_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='image',
        ),
    ]
