# Generated by Django 3.2.9 on 2021-12-13 11:43

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_indexpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=None),
        ),
    ]
